### ISSUE TITLE
SVG map query - bounds

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#10]
This is a bug - the query in func (f *fieldLatest) svg fetches all the sites, not just ones in the bbox.  This leads to sites plotting outside the expected image bounds.  Might need some care for queries that cross 180?

**Comment by crleblanc** [comment]
Here is an example that shows a point being plotted outside the map bounds: https://mtr-api.geonet.org.nz/field/metric/summary?width=800&typeID=voltage&bbox=LakeTaupo
