### ISSUE TITLE
Y Range for graph plots

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#126]
we need to stop using the thresholds to set the y range on the graphs. 
This limits the display of the graph significantly in some cases.
I think my preference would be to just use the extents of the current data to be shown in the plot
Open to other options if anyone has better ideas

**Comment by gclitheroe** [comment]
This shows the issue that Dave is referring to.  I used a grey box to show the yrange min and max and then when autoranging the y axis use the max data or may yrange to set the max of the yaxis.

https://metrics.geonet.org.nz/field/plot?deviceID=cellular-karameaschool&typeID=ping

If I don't include the max yrange in the autorange then the grey box goes out of the top of the plot area and the svg looks weired.

The y axis autorange decision will be happening here https://github.com/GeoNet/mtr/blob/master/ts/plot.go#L214

Chris - please could you look at some solutions?

It may be better to draw p.plt.Threshold.Min and p.plt.Threshold.Max as horizontal red lines and only plot them if they fall in the range of the y axis but scaled on the data?

**Comment by gclitheroe** [comment]
You haven't opened a pull request for this that I can find?

**Comment by crleblanc** [comment]
Ah I finally see what the issue is.  It looks like I didn't use GitHub to "fork" the repo, just cloned it on the command line and pushed to it.  I've solved that now, closed the old pull request (which was invalid) and have made a new pull request.  Should fix things, good to know you should do it "the github way".
