### ISSUE TITLE
Code review - could you add new features to mtr-api ?

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#135]
Hi,

I have severely re-factored the mtr-api code to try to

* make it more internally consistent
* easier to understand
* document some assumptions
* document how to add features.

@bpeng  please could you review the HEAD of my branch https://github.com/gclitheroe/mtr/tree/wip-mtr-api-polish and see if you could understand adding another table to the DB and some services to go with it (if you can't I have more work to do).

Maybe start with 

https://github.com/gclitheroe/mtr/blob/wip-mtr-api-polish/README.md
and also some of the assumptions outlined in https://github.com/gclitheroe/mtr/blob/wip-mtr-api-polish/mtr-api/domain.go

The rest of the code is really just handling requests and wiring.

@crleblanc and @junghao - do these changes answer some of the questions you have had?  Is it obvious enough how to add features.

@dc735 @ozym @quiffman - feedback welcome.  Especially for anything that might make this clearer.

FWIW the mtr-api is running the application metric caching code at the moment.  Seems ok.  I'll consider adding it for the field metrics etc based on comments on this issue.  I think mtr will always be DB and network constrained and not actually need horizontal scaling for the mtr-api server so adding some memory read caching to take pressure off the DB makes sense to me.

**Comment by ozym** [comment]
@gclitheroe I'm currently using a few json based end-points, as well as the protobufs. Happy to consider ditching these and going fully protobufs (leaving json for GeoJson suitable queries).

**Comment by gclitheroe** [comment]
Sweeve.  That would be good and probably a good first task for whoever puts their hand up and admits to being able to understand my code ;-)

**Comment by junghao** [comment]
This looks good. I think I can add new features by the instructions in README and existing codes.

**Comment by crleblanc** [comment]
Looks good to me too.  I was able to get some plots running from localhost.

**Comment by bpeng** [comment]
I can understand the logic, and add new feature and database schema, and extend the api. Code looks neat, the data reading and type checking is impressive.
