### ISSUE TITLE
Other types for the SVG maps

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#138]
The SVG map layers at https://metrics.geonet.org.nz/map are currently hard coded (and there may be some bugs here as well?).  This view should use the protobuf services and additional maps mentioned in #137 and #131 and #136 to decide what to display.

**Comment by bpeng** [comment]
@gclitheroe do we need add maps for DataComplenessType? 
This one is not working: https://mtr-api.geonet.org.nz/data/completeness/summary?bbox=NewZealand&width=800&typeID=gnss.1hz

**Comment by gclitheroe** [comment]
Yes please.
