### ISSUE TITLE
Fiftieth and ninetieth percentiles on latency plots

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#139]
The current data latency plots show just the mean latency e.g.,

https://mtr-api.geonet.org.nz/data/latency?siteID=AUCK&typeID=latency.gnss.1hz

This plots are generated in func (a *dataLatency) plot(

The plots show the avg(mean) latency in each time bin.  Please add two more series to the plots - max(fifty) and max(ninety) in each time bin.  These are the fiftieth and ninetieth percentiles for the metric.  

The three plot lines need labeling somewhere - maybe a horizontal colour key below and right on the plot?

It could be useful to look at app plotting code for handling multiple lines on a plot e.g., func (a *appMetric) loadCounters(

**Comment by junghao** [comment]
@gclitheroe Do we need the "latest" (the circle and label) for all series?

**Comment by gclitheroe** [comment]
Hmmmm good question.  I think at the moment leave it with just the mean as the latest value (it's the one people are monitoring at the moment).  If we get a request we can add it later (will need changes in ts lib).  

There is a request for interactive plots as well so when we look at that it may reduce the need for more complex other plots.
