### ISSUE TITLE
Interactive maps

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#140]
This may need further discussion about what to do for providing the services.

Please add interactive maps to mtr-ui.  These should have the same layers (metric types) as the SVG maps at https://metrics.geonet.org.nz/map and should appear on a tab in the mtr-ui.

They will need GeoJSON web services adding to mtr-api. 

Also there is some logic in mtr-ui to decide if a site is good or not, it may make sense to move this logic to a single set of rules in mtr-api

**Comment by gclitheroe** [comment]
This is the cleanest example I can find of GeoJSON from the DB.  For some reason I decided to pull the SQL queries out into consts here.  It's probably better to keep then right where they are called.

Notice the COALESCE so if there are no results in the agg set the GeoJSON is still valid.

https://github.com/GeoNet/haz/blob/master/geonet-rest/sql_queries.go#L20

**Comment by gclitheroe** [comment]
Yes please, use leaflet.  There are two options for hosting the Leaflet js lib.  

* in the mtr-ui application using a static file handler.
* use the one from our static CDN (which may need new versions adding let me know)

https://static.geonet.org.nz/leaflet/0.7.7/leaflet.js
https://static.geonet.org.nz/leaflet/0.7.7/leaflet.css

There is no right or wrong answer about which one to use.  If you need to modify the JS etc then it's going to be easier to host it from the mtr-ui app 

This project adds a static file handler for JS in the assets dir https://github.com/GeoNet/haz/blob/master/quakesearch/router.go#L19

**Comment by sorennh** [comment]
Did the API part to serve GeoJSON. 
I'm working on the leaflet client now. Just wondering about background layers - any preference (OSM vs basic map as in static version? Something else?)

**Comment by sorennh** [comment]
Also: do the interactive maps replace the static maps? Or will there be an extra tab?

**Comment by gclitheroe** [comment]
I suggest an extra tab.  Then we can user test and see if there is a reason to keep both.

I've been imagining that the static maps are good for a wall display.  Interactive maps maybe not so much.

Something like this http://geonetorigin-alpha.ap-southeast-2.elasticbeanstalk.com/earthquake/quakes/2016p439634
