### ISSUE TITLE
Source parameter for applications timer plots 

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#144]
The current application timer plot show the mean time for all timer sources in an application e.g.,

https://mtr-api.geonet.org.nz/app/metric?applicationID=mtr-api&group=timers

Please add an optional query parameter to this to allow the display of just a single timer source e.g.,

https://mtr-api.geonet.org.nz/app/metric?applicationID=mtr-api&group=timers&sourceID=applicationMetricHandler.PUT

On this new plot display the avg(mean), max(fifty) and max(ninety) metrics.

**Comment by junghao** [comment]
Not pretty sure what should this plot looks like.
Is this the plot you want?
@gclitheroe @crleblanc 

![screen shot 2016-06-07 at 10 41 50 am](https://cloud.githubusercontent.com/assets/8474881/15840217/9b7e766e-2c9c-11e6-849a-16de70ec6f5b.png)

**Comment by gclitheroe** [comment]
Yes I think so.  It's hard to tell how it should look till I see some real data but this looks like what I was thinking about.
