### ISSUE TITLE
Field device state services

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#147]
Please add a new service for field device state - this is things like "is the mains power on or off?"

The URL to send status will be POST to :

```
/field/state?deviceID=gps-taupoairport&typeID=mains&time=2015-05-14T21:40:30Z&value=on
/field/state?deviceID=gps-taupoairport&typeID=mains&time=2015-05-14T22:40:30Z&value=off
```

There also needs to be a service for tagging the state metrics.  The tagged results should be added to the tag search results as well.

The tables should be in the field schema and added to the file `field-schema.ddl`

The tables will be:

```
CREATE TABLE field.state_type (
	typePK SMALLINT PRIMARY KEY,
	typeID TEXT NOT NULL UNIQUE,
);
```

entries 

```
INSERT INTO field.state_type(typePK, typeID) VALUES(1, 'mains'); 
```

```
CREATE TABLE field.state (
	devicePK SMALLINT REFERENCES field.device(devicePK) ON DELETE CASCADE NOT NULL,
	typePK SMALLINT REFERENCES field.state_type(typePK) ON DELETE CASCADE NOT NULL,
	time TIMESTAMP(0) WITH TIME ZONE NOT NULL,
	state BOOLEAN NOT NULL,
	PRIMARY KEY(devicePK, typePK)
);
```

With this PK there will only be one value per device type in the table - it's a boolean state, not a time series.

```
CREATE TABLE field.state_tag(
  devicePK SMALLINT REFERENCES field.device(devicePK) ON DELETE CASCADE NOT NULL,
  typePK SMALLINT REFERENCES field.type(typePK) ON DELETE CASCADE NOT NULL,
  tagPK INTEGER REFERENCES field.state_tag(tagPK)  ON DELETE CASCADE NOT NULL,
  PRIMARY KEY(devicePK, typePK, tagPK)
);
```

The PUT handler will need an insert / update flow.  We need to check with @dc735 and @ozym how they want to handle state changes wrt to the timestamp changing.  Do they want:

1. the last timestamp and value sent.  
2. the timestamp for the last time the value changed?

Once this service is added for sending metrics and deployed we need to think about how to display it in mtr-ui and the services needed for getting the data out again.

**Comment by crleblanc** [comment]
Mostly through this issue.  Just one thing:

According to this site (https://jcalcote.wordpress.com/2008/10/16/put-or-post-the-rest-of-the-story/) it would seem that we should be using PUT instead of POST because we want it to be idempotent.  Actually you mention both PUT and POST, do we need to support both?

I haven't done anything about tagging yet, I'll look at that next.

**Comment by gclitheroe** [comment]
ooops - sorry on the mixing PUT and POST.  Which ever is consistent with the other endpoints.

PUT or POST are used to imply idempotent, they don't make it.  

Maybe the correct verb is something we can come back to later (but some of the endpoints are definitely not idempotent)

**Comment by crleblanc** [comment]
Ok, that's easier.  We aren't using POST anywhere else so PUT makes sense to me.

I'm trying to understand how tags are related to this table, just looking at the other tables to get an idea.

**Comment by crleblanc** [comment]
@dc735, @ozym:

Just wondering about the time issue.  What are your thoughts on the two possibilities @gclitheroe mentioned?

Currently I've implemented PUT (not POST) which requires a deviceID, typeID, time and value so the time is always updated (in this repo: https://github.com/crleblanc/mtr/tree/field_device_state).  Does that make sense?
