### ISSUE TITLE
Search by localities

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#159]
Since all the metrics are listed by place name we need to be able to search by place name. Htis could be either part of the same search for TAGS or a separate seach

Priority = None assigned

**Comment by dc735** [comment]
Updated issue heading to "Search by localities" as per the original wording from the network team request

**Comment by gclitheroe** [comment]
This means adding to the search function.  I would tend to keep it all in the same search function and type ahead if possible (deciding how to handle the search result / request may be complicated).

It means being able to search for the `hamiltonboyshighschool` part of the deviceID and then go to all metrics for that device.

https://metrics.geonet.org.nz/field/plot?deviceID=strong-hamiltonboyshighschool&typeID=disk.hd1

I guess this will need api and ui additions.

**Comment by junghao** [comment]
@dc Are all field devices' id using the rule of "device-type"-"locality"? 

e.g. "baycity-soundstage", "strong-arakuraschool"? So your search will be "soundstage" and "arakuraschool".

**Comment by dc735** [comment]
@junghao Yes that is correct
