### ISSUE TITLE
Tags on graphs used as links to search by tag

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#161]
Tags on graphs could be used as a link to search by tag

Priority = None assigned

**Comment by gclitheroe** [comment]
This sounds like a good idea to me.  The idea is that the tags become clickable links to search by tag on pages like this https://metrics.geonet.org.nz/field/plot?deviceID=rf2bluff-thepaps&typeID=voltage

I suggest putting the tags as links into the page above the plot.  Then possibly remove the tags from the plot which could then be let the plot be a little bigger.

**Comment by junghao** [comment]
@geoff While working on this ticket I founded that links are not clickable when svg being embedded into mtr-ui, but clickable with svg standalone(from mtr-api). 

Then I tried more search about this problem and founded that links inside SVG (with xlink:href) embedded as <img> are not clickable. But if we embed with <object> tag then it works.

See my demo copied from other web site: 
http://jwork.ddns.net:8008/svg.html

**Comment by junghao** [comment]
@gclitheroe While working on this ticket I founded that links are not clickable when svg being embedded into mtr-ui, but clickable with svg standalone(from mtr-api).

Then I tried more search about this problem and founded that links inside SVG (with xlink:href) embedded as  are not clickable. But if we embed with tag then it works.

See my demo copied from other web site: 
http://jwork.ddns.net:8008/svg.html

**Comment by gclitheroe** [comment]
So it looks to me that the ones in the object tag are not responsive?  I remember spending quit a lot of time making SVG images be responsive.  If you use the less common tags there are a lot of hacks needed for some browsers.

I prefer making the links above the image.  Then we can more easily style them to look like other links / actions.  What do you think?

**Comment by junghao** [comment]
Ok it'll be easier to do it from mtr-ui.
