### ISSUE TITLE
Zoom feature on graphs

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#166]
When we get well outside normal bounds it is useful to be able to zoom into a section of the graph or be able to set the x & y ranges.

Priority = None assigned

**Comment by crleblanc** [comment]
I believe this is resolved by the zoom feature of the interactive graphs, GeoNet/mtr#213.

Progressive loading is also handled by GeoNet/mtr#222.  The default 28 day time period uses a low resolution plot, then loads higher resolution data as the user zooms into a section of the graph.
