### ISSUE TITLE
Add scatter point graph option

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#167]
This my help see gaps in the graph when there is no data

Priority = None assigned

**Comment by gclitheroe** [comment]
Makes sense to me.  It's another plot parameter that would need adding to mtr-api and then a selector in mtr-ui.

FITS has scatter or line plots e.g.,

https://fits.geonet.org.nz/plot?networkID=VO&siteID=WI000&typeID=SO2-flux-a&type=scatter
https://fits.geonet.org.nz/plot?networkID=VO&siteID=WI000&typeID=SO2-flux-a&type=line

there might already be enough templates in `mtr/ts` for this.
