### ISSUE TITLE
build.sh bug

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#187]
There is a bug when building the Docker images.  The static binaries don't get cleaned out between builds for each sub project.  This means the last image built has all binaries in it.

The only issue it causes is the later images in the build process are much bigger than they need to be.

**Comment by gclitheroe** [comment]
@crleblanc - fixing this bug is pretty easy and I will do it.   I also have a proposal to change this script that it would be useful for you to comment on:

Instead of listing the sub projects to build docker images for we could use `find` and build images for all sub projects that have an env.list file in them.  It's a bit more convention over configuration.   Make it easier to just drop the script into another repo as well.

What do you think?

**Comment by gclitheroe** [comment]
Actually having written the proposal down above it doesn't really seem worth the change and I can see disadvantages (not being able to build just one image when needed in a repo that makes lots of images).

**Comment by crleblanc** [comment]
Ok.  Good to remove the unnecessary binaries.  Pretty simple fix too.

I can see why you'd prefer not to modify the behaviour.  It's a pretty minor difference anyway.
