### ISSUE TITLE
Display threshold values on plots

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#194]
Where ever there is a plot of a metric / latency etc that has a threshold then also display the lower and upper threshold values on the plot.

When the data values are far out of range it's hard to see what the thresholds are.  I suggest adding them in the plot title somewhere.

**Comment by crleblanc** [comment]
I've noticed this too.  The titles are getting a bit cluttered, especially when viewed on a mobile, but it's definitely something easy to add.  I've got a bugfix PR for mtr-api related to thresholds (GeoNet/mtr#230).  I could address this issue when I fix the mtr-ui display bugs (thresholds not being scaled, incorrect Y axis labels).

**Comment by crleblanc** [comment]
The threshold values are now displayed on the Y axis (if thresholds are used).
