### ISSUE TITLE
try out the completeness end points

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#200]
@junghao  has added the completeness endpoint and it's now deployed is deployed and metrics should show up in the UI.  

Endpoints as in the additions to the tests here https://github.com/GeoNet/mtr/commit/e7d38d11f7714e716c21a6a664d10384e31e253f#diff-f525b00a0658afde94886410101dc874R244

Please could you try it out?  Let us know if needs more features or changing etc.

**Comment by dc735** [comment]
@junghao &  @gclitheroe Now sending a data completeness metric
data/completeness?count=300&siteID=YALD&time=2016-07-07T04%3A05%3A05Z&typeID=gnss.1hz

Not getting any errors when sending
Not seeing any data showing up yet at ->
https://mtr-api.geonet.org.nz/data/completeness?siteID=YALD&typeID=gnss.1hz&resolution=five_minutes

**Comment by junghao** [comment]
Sorry I accidentally left a bug for this deploy. There's already a bug fix in the next PR. https://github.com/GeoNet/mtr/pull/203/commits/61c50a0b0c4dac9bfcaec24ff633c36aaf0adffc

**Comment by junghao** [comment]
The fix has been deployed and now the plot is good.
