### ISSUE TITLE
Add keyboard shortcut to search `/`

### ISSUE THREAD

**Issue by quiffman** [GeoNet/mtr#84]
I can imagine that the search by tag ID quickly becoming the killer feature in this new mtr-ui app.

As a user who prefers to quickly navigate _everything_ with keyboard, I would find a shortcut to navigate to the search input by pressing `/` incredibly useful.

FWIW, Google web-apps like GMail and Drive do exacely that, as well as others that we use like Atlassian Confluence (https://wiki.geonet.org.nz).

**Comment by gclitheroe** [comment]
@junghao - you referenced this.  Is it done?
